BG="#1e1e2e"
FG="#313244"
PRIMARY="#89b4fa"
SECONDARY="ffffff"
ACCENT="#a6e3a1"
FONT="JetBrainsMono Nerd Font"
TYPE="monospace"
OPACITY="0.6"
WALLPAPER="~/.config/backgrounds/wallpaper-10.jpg"
export BG FG PRIMARY SECONDARY ACCENT FONT TYPE OPACITY WALLPAPER
